name: build

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/go-riscv/go
  DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: 1.20/sid
          platforms: linux/riscv64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
