name: release

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write
  id-token: write # needed for signing the images with GitHub OIDC Token **not production ready**

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/go-riscv/go
  DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: sigstore/cosign-installer@v3.0.1
      - uses: anchore/sbom-action/download-syft@v0
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: 1.21/sid
          platforms: linux/riscv64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:sid
            ${{ env.IMAGE }}:1.21
            ${{ env.IMAGE }}:1.21.0
            ${{ env.IMAGE }}:1.21.0-sid
